### ISSUE TITLE
How exactly to use "window.touchEventInterceptors" ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [square/curtains#14]
I tried to use it on a new project:

```
window.touchEventInterceptors += TouchEventInterceptor { event, dispatch ->
  Log.d("AppLog", "touch")
  dispatch(event)
}
```

But it doesn't seem to do anything.

See attached:

[RecordAppSample.zip](https://github.com/square/curtains/files/6111830/RecordAppSample.zip)

**Comment by pyricau** [comment]
This seems to work for me, I see this in the logs:

```
D/AppLog: touch
```

Which Android version are you running this on?

**Comment by AndroidDeveloperLB** [comment]
@pyricau Tested again. Still doesn't work. It's Android R on Pixel 4.

Now tested with 1.1 version, and still got same issue.

Here, showing on emulator with Android R, even, including touch indicators:

[bm2ed2j0zg.zip](https://github.com/square/curtains/files/6319884/bm2ed2j0zg.zip)

[RecordAppSample.zip](https://github.com/square/curtains/files/6319885/RecordAppSample.zip)

**Comment by pyricau** [comment]
Ok, I reproduced it. I haven't found the exact explanation yet, but this probably has to do with doing it from inside the activity (vs an activity lifecycle callback). It works if you set the listener before calling `super.onCreate()`, but not if you set it after.

**Comment by pyricau** [comment]
Ok, so the window callback is replaced by two different calls:

- `super.onCreate(savedInstanceState)` sets it to `androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback`
- `setSupportActionBar(findViewById(R.id.toolbar))` sets it to `androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper`

**Comment by AndroidDeveloperLB** [comment]
@pyricau I don't understand. You say I should have used it differently?
If so please show me.

**Comment by pyricau** [comment]
`AppCompatActivity.setSupportActionBar()` behaves incorrectly. It replaces the callback but doesn't delegate to the currently set default and instead delegates to the previously set AppCompatWindowCallback. As a result, any callback set in between `AppCompatActivity.onCreate()` and `setSupportActionBar()` is replaced and not delegated to.

**Comment by pyricau** [comment]
This is a bug in Jetpack AppCompat, so I filed it here: https://issuetracker.google.com/issues/186791590

@AndroidDeveloperLB you can work around that bug. Instead of :

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        window.touchEventInterceptors += TouchEventInterceptor { event, dispatch ->
            Log.d("AppLog", "touch")
            dispatch(event)
        }
        setSupportActionBar(findViewById(R.id.toolbar))
    }
}
```

Move the interceptor to after `setSupportActionBar()`: 

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        setSupportActionBar(findViewById(R.id.toolbar))

        window.touchEventInterceptors += TouchEventInterceptor { event, dispatch ->
            Log.d("AppLog", "touch")
            dispatch(event)
        }
    }
}
```

**Comment by AndroidDeveloperLB** [comment]
@pyricau Happy you've found the reason. But why did you say you couldn't reproduce it before? Did you try the sample I've attached?

Anyway, after the changes it seems to work fine.

**Comment by pyricau** [comment]
> @pyricau Happy you've found the reason. But why did you say you couldn't reproduce it before? Did you try the sample I've attached?
> 

I had copy pasted the bits that seemed relevant instead of loading the project, sorry!

**Comment by pyricau** [comment]
The good news is, the next release of AppCompat will include a fix that prevents this from happening! https://android-review.googlesource.com/1696341

**Comment by AndroidDeveloperLB** [comment]
@pyricau Thank you!

**Comment by AndroidDeveloperLB** [comment]
@pyricau Say, I'm curious and I hope you can answer me on this:
Do you know which apps use this library? And where is it used? I wonder what cool usages can be of it.

**Comment by pyricau** [comment]
Any app that uses LeakCanary now also uses this library as a dependency. Aside from that, I know of a few apps but can't really share. One of these apps has a geometric shape, and another one has something to do with driving.

**Comment by AndroidDeveloperLB** [comment]
@pyricau LeakCanary is related to this library? I wonder what it uses from it.

Thank you for the fix.

**Comment by pyricau** [comment]
see https://square.github.io/leakcanary/changelog/#finer-grained-root-view-watching

**Comment by AndroidDeveloperLB** [comment]
@pyricau Toasts can leak?!
But they appear very temporarily...
You need to be very original to get Toasts leak...

But which part of this link is relevant to this library?

**Comment by pyricau** [comment]
![image](https://user-images.githubusercontent.com/557033/117899406-ea815c80-b27b-11eb-9995-5822e7109ab7.png)

**Comment by AndroidDeveloperLB** [comment]
@pyricau I mean what in there is using this library? Which functionality , for what purpose?
