### ISSUE TITLE
[Question] Is it safe to add an OnRootViewsChangedListener to Curtains.onRootViewsChangedListeners from an Activity?

### ISSUE THREAD

**Issue by TylerMcCraw** [square/curtains#24]
Is it safe call `Curtains.onRootViewsChangedListeners += OnRootViewsChangedListener { ...` from an Activity?
I'm assuming yes, but didn't know if there are any particular issues or any special cleanup needed with doing so.

The reason I'm asking is because I would like to avoid writing any business logic within my custom Application class and because I have a single Activity in my project, it makes sense to keep view/window-related listeners there.

Thanks!

**Comment by pyricau** [comment]
It should be safe to do this from anywhere, however you need to be careful to remove it when the activity is destroyed. Also remember that there can be several activities in create state at the same time so you might register several listeners.

**Comment by radityagumay** [comment]
> It should be safe to do this from anywhere, however you need to be careful to remove it when the activity is destroyed. Also remember that there can be several activities in create state at the same time so you might register several listeners.

How to remove the listeners? is  'Curtains.onRootViewsChangedListeners.clear()' works?
