### ISSUE TITLE
enable support for dropping jetifier

### ISSUE THREAD

**Issue by humblerookie** [square/curtains#26]
Can we switch to using the androidx components so that consumers can drop jetifier? Since this leakcanary is dependant 
on this, so consumers cannot drop the jetifier.

Currently it seems the class in questions is

`android.support.v7.view.WindowCallbackWrapper`

**Comment by r4zzz4k** [comment]
https://github.com/square/curtains/blob/41fd2ce387457e46efbc594a2b4cff172ffcc06d/curtains/src/main/java/curtains/internal/WindowCallbackWrapper.kt#L56-L66
Looking at the code above (tagged as 1.0.1, which is referenced by Leakcanary 2.7), the library already works without old Android Support library. If you found this issue with an automated tool like me, this seems to be a false positive.
This is actually a known issue, see https://github.com/dipien/bye-bye-jetifier/issues/22 and https://github.com/square/leakcanary/issues/2020 for further reference.

**Comment by humblerookie** [comment]
Thanks @r4zzz4k, makes sense. I did face this with the same plugin you've mentioned.

**Comment by r4zzz4k** [comment]
I'm hoping to get some clarifications at https://github.com/dipien/bye-bye-jetifier/issues/22 just to be 100% sure I'm not missing something, so feel free to follow that thread.

**Comment by pyricau** [comment]
thx!
