### ISSUE TITLE
onWindowFocusChanged callback

### ISSUE THREAD

**Issue by consp1racy** [square/curtains#3]
Hi, unless you're already working on it, i'd like to start working on a PR for `onWindowFocusChanged` callback.

One question, do we leverage `DispatchState` (like touch events) or not (like content changed, my favorite)?

**Comment by pyricau** [comment]
Hi!

So, interestingly, I had initially implemented `onWindowFocusChanged` (edb88f8cc948c050b66a98c7aaa5ee8edebcb3e4) and I later removed it when I realized that you can do:


```
view.viewTreeObserver.addOnWindowFocusChangeListener { hasFocus ->

}
```

It's more general though limited to API 18+.

Why do you need this?

> One question, do we leverage DispatchState (like touch events) or not (like content changed, my favorite)?

Welp, I've been hesitating. For content change I tried to follow the shape of the existing API. For touch events, however, the Android dispatch API isn't great, I never remember if I should return true or false, and I wanted to be able to intercept before and after. Hence the very different API. My thinking is along the lines of: follow the current Android API shapes, unless they're terrible.

**Comment by consp1racy** [comment]
Well, a) that API didn't occur to me ^^ and b) I was trying to stay away from VTO with all the floating and merging and how sometimes some things do get merged but it behaves differently depending on API level... This `Window.Callback` approach shines compared to that. Plus I'm happy I don't need to know about a view to track activity focus. Knowing about `Window` is already too much for my use case.

I'm building a sort of DPC app that needs to be able to enter lock task mode from multiple activities. For that an activity has to be not only resumed but also *focused* ([which nobody tells you exactly](https://developer.android.com/reference/android/app/Activity#startLockTask())). I didn't want to track it separately in each activity so I used `Application.ActivityLifecycleCallbacks`, which only gets you so far. But you can plug window callbacks in there, which allows you to track the window focus.

> follow the current Android API shapes

I agree, that means no return value and loop over everything, just like `Window.onContentChangedListeners`.

**Comment by pyricau** [comment]
Yep though you do get the `hasFocus` boolean: https://developer.android.com/reference/android/view/Window.Callback#onWindowFocusChanged(boolean)

I think this API makes sense, especially since the other one is API 18 min.

I intend to release very soon so let me know if you want to open up a PR!

**Comment by consp1racy** [comment]
Yep, I'll get on it
