### ISSUE TITLE
Add Proguard rules for WindowCallbackWrapper

### ISSUE THREAD

**Issue by pyricau** [square/curtains#32]
Copied over from https://github.com/square/leakcanary/issues/2280 by @mlilienberg 

### Description

My app is crashing when showing Dialog Fragments while R8 is turned on and with latest version 2.8.1.
I think the issue is that curtains dependency does not provide correct proguard rules. curtains.internal.WindowCallbackWrapper is accessing WindowCallbackWrapper from androidx and android.support via reflection. Adding proguard rules to app level solves the issue for me but it would be better if leakcanary or curtains could define those rules.

```
-keep class androidx.appcompat.view.WindowCallbackWrapper { *; }
-keep class android.support.v7.view.WindowCallbackWrapper { *; }
```

**Comment by CoXier** [comment]
I don't think is a good idea to add keep rule.

As a library, why not let user pass `androidx.appcompat.view.WindowCallbackWrapper` or `android.support.v7.view.WindowCallbackWrapper` into curtains.

**Comment by pyricau** [comment]
> As a library, why not let user pass androidx.appcompat.view.WindowCallbackWrapper or android.support.v7.view.WindowCallbackWrapper into curtains.

@CoXier what would the API look like for this? I'm not sure we'd be able to support this and keep Curtain working smoothly.
