### ISSUE TITLE
Support library dependency?

### ISSUE THREAD

**Issue by FelipeRRM-Carrot** [square/curtains#34]
Using the plugin canISayByeByeJetifier to detect libraries using Android's deprecated Support Libraries, it accuses Leak Canary as a problem because it uses Curtains. This is the issue it gives:

`curtains\internal\WindowCallbackWrapper$Companion$jetpackWrapperClass$2.class -> android.support.v7.view.WindowCallbackWrapper`

**Comment by pyricau** [comment]
Known issue, canISayByeByeJetifier is wrong, and they supposedly fixed this in the latest version.
