### ISSUE TITLE
Window null for Jetpack Compose PopupLayout root view

### ISSUE THREAD

**Issue by AnupKhanal** [square/curtains#39]
I have found a screen to have multiple root views when using Jetpack Compose DropDownMenu and the DropDownMenu is visible. The first is a standard DecorView, the second is a PopupLayout.

When acquiring the window of the PopupLayout through rootView.phoneWindow, null is returned.

A nudge towards the right direction to acquire the window of the PopupLayout would be greatly appreciated.

**Comment by pyricau** [comment]
Can you provide an example repro? Android views can't have multiple root views, so something else is going on. Happy to take a look if you can repro.

**Comment by AnupKhanal** [comment]
Example repo: https://github.com/AnupKhanal/CurtainsIssue

Printing the root views and their windows using this callback:
```
        Curtains.onRootViewsChangedListeners += OnRootViewsChangedListener { view, added ->
            println("root $view ${if (added) "added" else "removed"}")
            println("window for view ${view.phoneWindow}")
        }
```

Once the composable element that opens up a DropDownMenu is clicked, the following logs are printed:
```
root androidx.compose.ui.window.PopupLayout{336244 V.E...... ......I. 0,0-0,0 #1020002 android:id/content} added
window for view null
```
Issue: The window for the DropDownMenu is null. 

I don't need this to be fixed anymore, but thought it might be useful for somebody else working with compose.

**Comment by pyricau** [comment]
Turns out, this is because PopupLayout is not backed by a PhoneWindow. So null is normal here. 

In 70146b26d65de1f0647298b4623fc9d0558a54d8 I made sure PopupLayout is now reported as a POPUP_WINDOW type (which don' have a PhoneWindow)
